server:
  port: 2580

mybatis:
  config-location: classpath:mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.ddw.pictureUploadServiceImpl.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: prctureUpload_img
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/t?&serverTimezone=GMT%2B8              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#  http:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 50MB
#      enabled: true #开启

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:10001/eureka